### ISSUE TITLE
Cannot assign requested address when run django_dramtiq with rabbitmq in docker-compose

### ISSUE THREAD

**Issue by DmitriyDmytruk** [kevinappy/django_dramatiq#2]
**settings.py**
```
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.rabbitmq.RabbitmqBroker",
    "OPTIONS": {
        "url": os.getenv("RABBITMQ_URL"),
    },
    "MIDDLEWARE": [
        "dramatiq.middleware.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
        "django_dramatiq.middleware.AdminMiddleware",
    ],
}
```

**docker-compose**
```
version: "3"

services:
  web:
    image: 'local'
    build:
      context: .
      dockerfile: deploy/Dockerfile-dev
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - sortif-network

  rabbitmq:
    image: rabbitmq:latest
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - sortif-network

  dramatiq_worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: deploy/Dockerfile-dev
    environment:
      dramatiq_prom_host: dramatiq_worker
      dramatiq_prom_port: 9191
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/src
    command: ./manage.py rundramatiq
    networks:
      - sortif-network

networks:
  sortif-network:
```

`RABBITMQ_URL=amqp://localhost:5672`

When I run `docker-compose up` I get error
```
dramatiq_worker_1  | [2021-01-27 15:12:44,467] [PID 15] [Thread-3] [dramatiq.worker.ConsumerThread(default.DQ)] [CRITICAL] Consumer encountered a connection error: AMQPConnectionError: (AMQPConnectorSocketConnectError: OSError(99, 'Cannot assign requested address'),)
```
But `rabbitmq` and `web` services are started.

When `RABBITMQ_URL=amqp://rabbitmq:5672` I run `docker-compose up` I get the same error.
